name: Generate Contribution Animations

on:
  # Se ejecuta automáticamente todos los días a medianoche
  schedule:
    - cron: "0 0 * * *"
  # Permite ejecutarlo manualmente desde la pestaña Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Genera el GIF del juego con tu usuario
      - uses: Platane/snk@v3
        with:
          github_user_name: mangodev-hub
          outputs: |
            dist/space-shooter.gif?palette=github-dark
            dist/github-contribution-grid-snake.svg

      # Sube los archivos generados a la rama 'output'
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
